### ISSUE TITLE
Roadmap and missing features

### ISSUE THREAD

**Issue by MrKevinWeiss** [inetrg/inet-nm#3]
A number of planned features...

- [ ] Add optional power control
  - [ ] Check if power control available for which boards
  - [ ] Turn all ports on by default whenever checking connection
  - [ ] Turn all unused off commissioned nodes by default once the action is complete
  - [ ] flags to prevent power options
  - [ ] Generic command to turn on all ports or specific nodes
  - [ ] Caching usb locations
- [ ] cleanup exception handling
- [ ] remove all or one board
- [ ] allow user boards that will not get overwritten
- [ ] Nice readme with some gifs of usage
- [ ] Add a CLI way and example get the port live based off UID to handle reconnecting within tmux session
- [ ] Improve getting started
- [ ] Add a session or exec timeout that will abort if the call takes too long
- [ ] Add tests that go through the cli

**Comment by MrKevinWeiss** [comment]
Some things that should be done before having actual users:
- power control
- versioned configs
- remove CLI settable config files
- move some caches into the .cache/ folder
- simpler examples
